name="newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-01-04"

[[d1_databases]]
binding = "DB"
database_name = "newsnow"
database_id = "26f8a557-4ab9-4240-b4dd-d59780148d77"
